### ISSUE TITLE
[Documentation | Submission] Graphics

### ISSUE THREAD

**Issue by chuahxinyu** [chuahxinyu/devrev-hackathon#11]
**Sub-tasks**
- [ ] `/images/icon.png`
  - 128 x 128px
  - where it will be:
    - in Marketplace
    - ![image](https://user-images.githubusercontent.com/66938425/147490402-0d1a4bb7-b7db-4e74-9962-66da54116bf7.png)
    - ![image](https://user-images.githubusercontent.com/66938425/147490507-3f068e06-9752-4ee6-b87f-91fd6581d82c.png)
- [ ] `/images/banner.png
  - where it will be:
    - in Marketplace
    - ![image](https://user-images.githubusercontent.com/66938425/147490549-65d6df39-998b-4b88-a5d8-262ae4efbeab.png)
- [ ] `/images/thumbnail.png/.gif`
  - 1200 x 800px
  - where it will be:
    - in Devpost
- [ ] `/images/docs/<section-name>/section-heading.png`
  - where it will be:
    - in README.md
- [ ] [TBD] sidebar icon (svg)
- [ ] [TBD] view icons (svg)
  - dark
  - light

**Resources**
- Figma
