### ISSUE TITLE
[Docstring] Generate

### ISSUE THREAD

**Issue by chuahxinyu** [chuahxinyu/devrev-hackathon#8]
**Descirption**
- what is it
- add some screenshots or gifs to further illustrate the stuff
- ...

**Affected files**
- `extension..ts`
- `README.md`
- `/src/.ts`

**Sub-tasks**
- [ ] User Guide
- [ ] Learning Stuff
  - [ ] @PizzasRDelicious learn JavaScript/TypeScript
  - [ ] @PizzasRDelicious make HelloWorld Extension
- [ ] VSCode Extension
  - [ ] command
  - [ ] keybinding shortcut
  - [ ] add to context menu
- [ ] OpenAI
- [ ] Contribution Guide

**Resources**
- ...

**Comment by chuahxinyu** [comment]
Blocker: error when trying to make `POST` request using `axios` to get OpenAI response
The error messages:
```
rejected promise not handled within 1 second: Error: certificate has expired

stack trace: Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.onhandshakedone (_tls_wrap.js:706:12)
	at TLSWrap.callbackTrampoline (internal/async_hooks.js:131:14)
```

What I've tried/am trying
https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired
